### ISSUE TITLE
Equations are not centering by default

### ISSUE THREAD

**Issue by CosmoGao** [Tedxz/xjtuthesis-x#3]
While testing the templete, I found that when I use the environment as that:
```LaTex
\begin{equation}
    equation
\end{equation}
```
the equation will indent for 4 bytes, but on centering.

**Comment by CosmoGao** [comment]
Suggest that use the package amsmath without fleqn.

**Comment by Tedxz** [comment]
According to the official manual, **the equation should be started in a new line and intended by two (Chinese) characters, instead of centering**.

The newest version (2017) of official manual can be obtained from [here](http://pts.xjtu.edu.cn:8080/shownews.aspx?newsno=gEwvWdvAqO59MhsUwS4zZw....). The specification of the equation format is on the page 26.

`xjtuthesis` and `xjtuthesis-x` are designed according to the specifications of the official manual, and should be updated if the specifications changes in newer version of the official manual. If you (and other users and contributors) find that the specifications changes or the design of `xjtuthesis-x` breaks the specifications, you are welcome to open an issue or send a pull request.

Thank you all the same.

![image](https://cloud.githubusercontent.com/assets/7670294/22693206/3bbc3f5c-ed7d-11e6-9585-bdc22436b403.png)

**Comment by Acmece** [comment]
Can anyone reopen this issue?
According to the  [newest version (2018) ](http://pts.xjtu.edu.cn:8080/shownews.aspx?newsno=zDa+Hsud61knwW2b+HIsNw....). A specification changes in this version of the official manual:

![image](https://user-images.githubusercontent.com/25225110/39856621-34b513de-5463-11e8-855d-dcae8e81c7a0.png)

Could you update this template @Tedxz ?
Thank you very much.

**Comment by Tedxz** [comment]
@Acmece Thank you for your update. Since the specification has changed, the template should be updated accordingly.

**Comment by Tedxz** [comment]
@Acmece I've updated the template, and the equations are now centered. You can try it out now.
BTW, would you like to find out if there are any other changes in the 2018 version? You may open another issue on the new changes so that we can keep the template up to date.

**Comment by Acmece** [comment]
@Tedxz Thank you, that's my pleasure.
