### ISSUE TITLE
Reference can not work

### ISSUE THREAD

**Issue by evanlu14** [Tedxz/xjtuthesis-x#4]
When I am running under the framwork directory, I found that the reference can not work normally. Here is the makefile result:
```bash
➜  framework git:(master) ✗ make bachelor
mkdir -p build
xelatex -output-directory build/ --no-pdf --interaction=nonstopmode bachelor.tex >/dev/null
bibtex bachelor || true
I couldn't open file name `bachelor.aux'
xelatex -output-directory build/ --no-pdf --interaction=nonstopmode bachelor.tex >/dev/null
xelatex -output-directory build/ --interaction=nonstopmode bachelor.tex >/dev/null
```
As you can see, bibtex can not find `bachelor.aux`.

**Comment by Tedxz** [comment]
Hi Joezc, 

Since you did not provide a MWE ([minimum working example](http://minimalbeispiel.de/mini-en.html)), I do not know what is happening to you exactly. However, I'll briefly introduce how bibtex works, which may help you to resolve your issue.

Here `bibtex` command is used to generate a reference list in the thesis. If you did not insert a reference list, the `bibtex` command can be skipped. Thus, here we use `|| true` to make sure that if `bibtex` does not find the related files and exited with an error, the compilation can still proceed. In this case, you can dismiss this warning.

If you want to insert a reference list in the thesis, you have to:

1. Prepare the database (`*.bib`). Assume that it is named `bibliography.bib`.
2. Use `\xjtubib{bibliography}` in the `.tex` file to insert the reference list.

Please check if you are doing right.

If this is not helping, please provide a MWE so that I can go further with your issue.

**Comment by Tedxz** [comment]
Hi @Joezc , did my last comment solve your problem? I wonder if there are still some problems or we can close this issue?

**Comment by Tedxz** [comment]
Closing this issue for now.

**Comment by evanlu14** [comment]
What I mean here is that maybe the following line has some problem:

https://github.com/Tedxz/xjtuthesis-x/blob/55ecfc26231fe2b455e5ba8fee4513a82aad492a/framework/Makefile#L19

Since xelatex generate `bachelor.aux` under `build` directory, so it generate this error message:
```
I couldn't open file name `bachelor.aux'
```

So maybe it should be change to `bibtex $(BUILDPATH)/$* || true`
